export enum storageKey {
  USER_ID = 'USER_ID',
  LOCAL_LANG = 'LOCAL_LANG',
  ETAG_LOAD_SYMBOL_LIST = 'ETAG_LOAD_SYMBOL_LIST',
  WATCH_LIST_BOARD_SETTINGS = 'WATCH_LIST_BOARD_SETTINGS',
  NFC_SCANNED = 'NFC_SCANNED',
}
